# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1f413df3291a0da0edba2e2708f800c55a6b2d6b0a65c55fe5c38a0b10102321c70422f099b499ae1a79cb540151af2053541e602ba65604cb63bee0607f541

test:
  secret_key_base: a03f3ab6062b68ceb50c708e72736d6fa7a27203c72c72c0cdd63e1e37a9bb4e5d8b81d5fedfb1eab2474129f000a0f0a29d399222bcf1c627597c3315d34cc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
